CREATE TABLE IAM.INSEE_DECES_SEJOUR
AS SELECT NIP, MAX(LAST_VISIT_DATE) AS LAST_VISIT_DATE
FROM (
SELECT DISTINCT
    NIP,
    MAX(IAM_REFERENTIEL.IMS_SEJOUR_WITHOUT_DOUBLON.DATE_SORTIE_VENUE) OVER(PARTITION BY IAM_REFERENTIEL.IMS_SEJOUR_WITHOUT_DOUBLON.NIPATIENT) LAST_VISIT_DATE
  FROM
    IAM_REFERENTIEL.IMS_SEJOUR_WITHOUT_DOUBLON
    WHERE  IAM_REFERENTIEL.IMS_SEJOUR_WITHOUT_DOUBLON.VENUE_SUPPRIME='N' -- VISIT NOT DELETED
    
  UNION ALL
  
  SELECT DISTINCT
    PATID NIP,
    MAX(PIL.SRV_VENQ.VEN_DSO) OVER(PARTITION BY PIL.SRV_VENQ.PATID) LAST_VISIT_DATE
  FROM
    PIL.SRV_VENQ
  WHERE
    PIL.SRV_VENQ.SUPPRIME='N' -- VISIT NOT DELETED
)
GROUP BY NIP;


CREATE INDEX INDEX_INSEE_DECES_SEJOUR_NIP 
ON IAM.INSEE_DECES_SEJOUR(NIP);