SELECT
-- NIP
SRV.IMS_PATIENT.NIP, 

-- NOM
SRV.IMS_PATIENT.NOM SPA_NOM_USUEL,
SRV.IMS_PATIENT.PATRONYME SPA_NOM_NAISS,

-- PRENOM
SRV.IMS_PATIENT.PRENOM SPA_PRENOM_USAGE,
SRV.IMS_PATIENT.PRENOM SPA_PRENOM_ETAT_CIVIL,

-- DATE NAISSANCE
SRV.IMS_PATIENT.DATE_NAISSANCE SPA_DATE_NAISS,

-- PLACE OF BIRTH 
SRV.IMS_PATIENT.CPNAIS SPA_CP_VILLE_NAISS,
SRV.IMS_PATIENT.VILLENAIS SPA_VILLE_NAISS,
SUBSTR(SRV.IMS_PATIENT.CPNAIS,1,2) SPA_DEP_NAISS,
PAYS_NAISSANCE SPA_LIBELLE_PAYS_NAISSANCE,

-- SEXE
SRV.IMS_PATIENT.SEXE SPA_SEXE,

-- DEP actuel
SUBSTR(SRV.IMS_PATIENT.CPVILLE,1,2) DEP_HABITE,

-- LAST_VISIT_DATE
IAM.INSEE_DECES_SEJOUR.LAST_VISIT_DATE

FROM 
IAM.INSEE_DECES_SEJOUR,
SRV.IMS_PATIENT

WHERE
IAM.INSEE_DECES_SEJOUR.NIP = SRV.IMS_PATIENT.NIP
AND EXTRACT(YEAR FROM SRV.IMS_PATIENT.DATE_NAISSANCE)= ${YEAR_BIRTH} 
