  CREATE TABLE "IAM"."INSEE_DECES" 
   (	
   "id" VARCHAR2(50 BYTE),   
   "NOM" VARCHAR2(255 BYTE), 
   "PRENOM" VARCHAR2(255 BYTE), 
   "PRENOM1" VARCHAR2(255 BYTE), 
   "PRENOM2" VARCHAR2(255 BYTE), 
   "PRENOM3" VARCHAR2(255 BYTE),
   "SEXE" CHAR(1 BYTE), 
   "DATE_NAISSANCE_STR" VARCHAR2(50 BYTE), 
	-- "DATE_NAISSANCE" DATE, 
	"ANNEE_NAISSANCE" NUMBER(*,0), 
	"MOIS_NAISSANCE" NUMBER(*,0), 
	"JOUR_NAISSANCE" NUMBER(*,0), 
	
   "CODE_LIEU_NAISSANCE" VARCHAR2(25 BYTE), 
   "DEPARTEMENT_NAISSANCE" VARCHAR2(2 BYTE),
   "LIEU_NAISSANCE" VARCHAR2(255 BYTE),
	"PAYS_NAISSANCE" VARCHAR2(255 BYTE), 

   "DATE_DECES_STR" VARCHAR2(10 BYTE), 
	-- "DATE_DECES" DATE, 
	"ANNEE_DECES" NUMBER(*,0), 
	"MOIS_DECES" NUMBER(*,0), 
	"JOUR_DECES" NUMBER(*,0), 
	"CODE_LIEU_DECES" VARCHAR2(25 BYTE), 
	"DEPARTEMENT_DECES" VARCHAR2(2 BYTE), 
	"NUMERO_ACTE_DECES" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IAM_DATA" ;

  CREATE INDEX "IAM"."INDEX2" ON "IAM"."INSEE_DECES" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IAM_DATA" ;

  CREATE INDEX "IAM"."INDEX3" ON "IAM"."INSEE_DECES" ("PRENOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IAM_DATA" ;

  CREATE BITMAP INDEX "IAM"."INDEX4" ON "IAM"."INSEE_DECES" ("SEXE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IAM_DATA" ;

  CREATE INDEX "IAM"."INDEX5" ON "IAM"."INSEE_DECES" ("DATE_NAISS_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IAM_DATA" ;

  CREATE INDEX "IAM"."INDEX6" ON "IAM"."INSEE_DECES" ("DEPARTEMENT_DECES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IAM_DATA" ;